import { FC } from 'react';
import { Metadata } from 'next';

import ContainerContact from '@/components/Containers/Contact/Contact';

export const metadata: Metadata = {
  title: 'Contact TOL',
  description: 'Generated by create next app',
};

const Contact: FC = () => {
  return <ContainerContact />;
};

export default Contact;
